###服务启动端口号
server:
  port: 8888
  
  
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: springcloud-actuator-demo
    #security:
      #user:
       # name: xiangjiao
        #password: bunana

##feign中使用断路器，默认是没有开启的，需要在配置文件中开启        
feign:
  hystrix:
    enabled: true

###服务注册到eureka地址
eureka:
  client:
    registry-fetch-interval-seconds: 20
    #registryFetchIntervalSeconds: 20
    service-url:
       defaultZone: http://localhost:10000/eureka/
  #自己是服务，需要注册至服务注册中心上
    register-with-eureka: true
  #如果需要通信，必须运行此服务可以拉去别的服务的注册信息
    fetch-registry: true
    
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-renewal-interval-in-seconds: 5
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-expiration-duration-in-seconds: 7
    
##增加Actuator相关配置
management.server.port: 8889 ##管理端口调整为 8889，独立的端口可以作安全控制
## actuator的访问路径(修改访问路径，2.0之前默认是/，2.0默认是/actuator)
management.endpoints.web.base-path: /xiangjiao 
#开放所有页面节点  默认只开启了health、info两个节点
management.endpoints.web.exposure.include: "*"
#公开中的所有端点，除去 env(不配置这个启动会直接报错项目停止)
management.endpoints.web.exposure.exclude: "env"
#显示健康具体信息  默认不会显示详细信息  
management.endpoint.health.show-details: always
       