###服务启动端口号
server:
  port: 10001
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-bunana-consumer-10001
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:10000/eureka
       
  #自己是服务，需要注册至服务注册中心上
    register-with-eureka: true
  #如果需要通信，必须运行此服务可以拉去别的服务的注册信息
    fetch-registry: true