###服务启动端口号
server:
  port: 3000
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: springcloud-config-service

## Config Server 配置中心Service配置信息    
## 配置文件所在的 git 仓库地址    
spring.cloud.config.server.git.uri: https://github.com/765199214/springcloud2.0-config-service.git
## 配置文件再哪个文件夹下
spring.cloud.config.server.git.search-paths: respo
## 配置 clone-on-start 启动时就clone仓库到本地，默认是在配置被首次请求时，config server 才会 clone git 仓库
spring.cloud.config.server.git.clone-on-start: true
## 配置默认 git clone 至指定的磁盘或文件夹内(linux 只有一个 / 根；windows 会进入项目所在的磁盘下)
spring.cloud.config.server.git.basedir: /data/config server/
## 配置文件在 git 仓库上的某个分支
#spring.cloud.config.server.git.default-label: master
## 如果是私有仓库，需要在此处配置账号密码信息
#spring.cloud.config.server.git.username: 
#spring.cloud.config.server.git.password: 


####服务注册到eureka地址
#eureka:
#  client:
#    service-url:
#           defaultZone: http://localhost:10000/eureka/
#       
#  #自己是服务，需要注册至服务注册中心上
#    register-with-eureka: true
#  #如果需要通信，必须运行此服务可以拉去别的服务的注册信息
#    fetch-registry: true
#    
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
#    lease-renewal-interval-in-seconds: 5
#    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
#    lease-expiration-duration-in-seconds: 7