###服务启动端口号
server:
  port: 10001
  
##feign中使用断路器，默认是没有开启的，需要在配置文件中开启        
feign:
  hystrix:
    enabled: true
    
        
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-bunana-consumer-hystrix-feign
#    main:
#      allow-bean-definition-overriding: true

## feign整合Hystrix实现超时降级配置
hystrix:
  command:
    default:
      execution: ## 超时配置
        isolation:
          thread:
            timeoutInMilliseconds: 2000   #设置请求超时时间，默认1秒，超过指定的时间后，触发降级
            
                   
###服务注册到eureka地址
eureka:
  client:
    #以下两种方式都可以
    #registry-fetch-interval-seconds: 20
    registry:
        fetch:
            interval:
                seconds: 20
    #registryFetchIntervalSeconds: 20
    service-url:
       defaultZone: http://localhost:10000/eureka/
       
  #自己是服务，需要注册至服务注册中心上
    register-with-eureka: true
  #如果需要通信，必须运行此服务可以拉去别的服务的注册信息
    fetch-registry: true
    
    
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-renewal-interval-in-seconds: 5
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-expiration-duration-in-seconds: 7
    
    