###服务启动端口号
server:
  port: 10001
###服务名称(服务注册到eureka名称)  
spring:
    application:
        name: app-bunana-consumer
    security:
      user:
        name: xiangjiao
        password: bunana
###服务注册到eureka地址
eureka:
  client:
    service-url:
       defaultZone: http://xiangjiao:bunana@localhost:10000/eureka/,http://xiangjiao:bunana@localhost:11000/eureka/,http://xiangjiao:bunana@localhost:12000/eureka/
       
  #自己是服务，需要注册至服务注册中心上
    register-with-eureka: true
  #如果需要通信，必须运行此服务可以拉去别的服务的注册信息
    fetch-registry: true
    
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
    lease-renewal-interval-in-seconds: 5
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-expiration-duration-in-seconds: 7
    
    